version: '3'
services:
    odoo:
       image: odoo:latest
       ports:
           - "8069:8069"
       depends_on:
           - db
       volumes:
           - ./odoo:/mnt/extra-addons
    db:
       image: postgres:13
       environment:
           - POSTGRES_USER=odoo
           - POSTGRES_PASSWORD=odoo
           - POSTGRES_DB=postgres
